export default [
    {
        title: 'Projeto 1',
        description: 'Projeto 1',
        status: 'Em andamento',
        type: 'Backend',
        initial_date: '28/05/2011',
        final_date: '28/05/2013',
        link: 'https://github.com/',
        brand: 'assets/images/logoJava.svg',
    },
    {
        title: 'Projeto 2',
        description: 'Projeto 1',
        status: 'Finalizado',
        type: 'Frontend',
        initial_date: '28/05/2011',
        final_date: '28/05/2013',
        link: 'https://github.com/',
        brand: 'assets/images/logoPhp.svg',
    },
    {
        title: 'Projeto 3',
        description: 'Projeto 1',
        status: 'Em andamento',
        type: 'Backend',
        initial_date: '28/05/2011',
        final_date: '28/05/2013',
        link: 'https://github.com/',
        brand: 'assets/images/logoJavaScript.svg',
    },
    {
        title: 'Geren. de restaurantes',
        description: 'PHP, Laravel',
        status: 'Finalizado',
        type: 'Full Stack',
        initial_date: '19/10/2022',
        final_date: '25/10/2022',
        link: 'https://github.com/wesquel/gerenciador-de-restaurante/',
        brand: 'assets/images/logoPhp.svg',
    },
];
