export default [
  {
    title: "Serv. autenticação Spring",
    description: "Java, Spring",
    status: "Finalizado",
    type: "Back-end",
    initial_date: "02/2024",
    final_date: "02/2024",
    link: "https://github.com/wesquel/study_projects/tree/main/java/authentication",
    brand: "assets/images/logoJava.svg",
  },
  {
    title: "Moni. Água com MQTT",
    description: "Java, Spring",
    status: "Finalizado",
    type: "Back-end",
    initial_date: "04/2023",
    final_date: "12/2023",
    link: "https://github.com/wesquel/Water-Monitor/commits/main/water_server",
    brand: "assets/images/logoJava.svg",
  },
  {
    title: "Plataforma de Estágios",
    description: "PHP, Laravel",
    status: "Finalizado",
    type: "Full Stack",
    initial_date: "04/2022",
    final_date: "12/2022",
    link: "https://github.com/wesquel/SIAAE",
    brand: "assets/images/logoJavaScript.svg",
  },
  {
    title: "Geren. de restaurantes",
    description: "PHP, Laravel",
    status: "Finalizado",
    type: "Full Stack",
    initial_date: "10/2022",
    final_date: "10/2022",
    link: "https://github.com/wesquel/gerenciador-de-restaurante/",
    brand: "assets/images/logoPhp.svg",
  },
  {
    title: "Controle Estacionamento",
    description: "Java, Spring",
    status: "Finalizado",
    type: "Back-end",
    initial_date: "04/2022",
    final_date: "04/2022",
    link: "https://github.com/wesquel/Parking-Control-API",
    brand: "assets/images/logoJava.svg",
   },
   {
    title: "AppWords",
    description: "Kotlin",
    status: "Finalizado",
    type: "Mobile",
    initial_date: "10/2021",
    final_date: "11/2021",
    link: "https://github.com/wesquel/AppWords",
    brand: "assets/images/logoKotlin.svg",
   },
   {
    title: "DesertClickApp",
    description: "Kotlin",
    status: "Finalizado",
    type: "Mobile",
    initial_date: "10/2021",
    final_date: "10/2021",
    link: "https://github.com/wesquel/AppWords",
    brand: "assets/images/logoKotlin.svg",
   },
   {
    title: "TipTimeApp",
    description: "Kotlin",
    status: "Finalizado",
    type: "Mobile",
    initial_date: "10/2021",
    final_date: "10/2021",
    link: "https://github.com/wesquel/TipTimeApp",
    brand: "assets/images/logoKotlin.svg",
   },
   {
    title: "IAs simples",
    description: "PHP, Laravel",
    status: "Finalizado",
    type: "Full Stack",
    initial_date: "07/2020",
    final_date: "08/2020",
    link: "https://github.com/wesquel/CS50AI",
    brand: "assets/images/logoPython.svg",
   },
];
